# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'BusinessReviewsHub' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  pod 'Alamofire', '~> 4.0'
  pod 'EVReflection'
  pod 'MBProgressHUD'
  pod 'AlamofireImage'

  # Pods for BusinessReviewsHub

  target 'BusinessReviewsHubTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'BusinessReviewsHubUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
